[server]
# Ensure the app listens on the correct port for deployment
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[theme]
# Theme settings based on your current local look
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

[browser]
gatherUsageStats = false
